### ISSUE TITLE
Question: useful for forcing stereo mode?

### ISSUE THREAD

**Issue by djay** [kodi-adsp/adsp.basic#14]
Is it possible when configured with 5.1 to send stereo as multichannel in order to bypass the receivers DSP processing? I'm looking for a way to play music in stereo and movies in prologic2 on my receiver.

**Comment by AchimTuran** [comment]
Please do not use our Github issues page for asking questions. It is mainly used for development and reporting bugs.
If you have questions about AudioDSP and Kodi please use our (subforum)[http://forum.kodi.tv/forumdisplay.php?fid=235]

Back to your question. This is currently not possible, because we would need a kind of profile manager.
